### ISSUE TITLE
redirect uri sub-path

### ISSUE THREAD

**Issue by epichub** [pdobsan/oama#40]
My orgs OAUTH azure application requires the redirect_uri to end in getToken (its made for https://github.com/harishkrupo/oauth2ms) - i cannot get "redirect_uri: http://localhost:5000/getToken" to work with oama - does the config support it?

**Comment by pdobsan** [comment]
On Wed, Apr 03, 2024 at 01:12:33AM -0700, Bjørn Magnus Mathisen wrote:
> cannot get "redirect_uri: http://localhost:5000/getToken" to work with
> oama - does the config support it?

No it does not. In fact, the redirect_uri is always
http://localhost:<port>/. The option is a remnant from an early version.
I intend to remove it and only the port number would be configurable.
