### ISSUE TITLE
Specifying auth_scope for services (caldav, carddav)

### ISSUE THREAD

**Issue by dezeroku** [pdobsan/oama#45]
Hi, first of all thanks for all the work you've put into this project!

I've recently switched from `mailctl` to `oama` and I am struggling with defining caldav and carddav scopes to be authed with.
With `mailctl` it was possible to create `services.yml`, such as:
```
google:
  ...
  auth_scope: https://mail.google.com/ https://www.googleapis.com/auth/carddav https://www.googleapis.com/auth/calendar
```
and then use the obtained tokens with utils like [vdirsyncer](https://github.com/pimutils/vdirsyncer).

In `oama` the scope seems to be [hardcoded in config](https://github.com/pdobsan/oama/blob/main/lib/OAMa/Environment.hs#L80).
Or maybe it can already be set via the config file but I missed how to do it?

**Comment by pdobsan** [comment]
> in oama the scope seems to be [hardcoded in config](https://github.com/pdobsan/oama/blob/main/lib/OAMa/Environment.hs#L80).
Or maybe it can already be set via the config file but I missed how to do it?

Yes, the services are hardcoded at the moment. I can  make some fields configurable again as reasonable needs arises. `auth_scope` seems to be one, I'll look into it.

**Comment by pdobsan** [comment]
I believe that [oama 0.11 release](https://github.com/pdobsan/oama/releases/tag/0.11) solves your problem.

**Comment by dezeroku** [comment]
Indeed, I can set the `auth_scope` with the version `0.11`.
Thanks a lot for the quick help!

**Comment by pdobsan** [comment]
Close as solved.
