### ISSUE TITLE
Oama authorize only listens to localhost by default

### ISSUE THREAD

**Issue by radupotop** [pdobsan/oama#46]
Oama authorize only listens to IPv6 by default.

```
> netstat -tulpn|grep 8080                                                                                          
tcp6       0      0 ::1:8080                :::*                    LISTEN      10610/oama    
```

Is there any way i can get it to listen to IPv4?

Thanks

**Comment by pdobsan** [comment]
> Oama authorize only listens to IPv6 by default.

Well, oama binds to `localhost` so whatever is the host's  network setup that what determines
where it is listening. That is an external problem.

**Comment by radupotop** [comment]
Ok that makes sense. I there any way I can have oama listen to `0.0.0.0`  instead of localhost? I need to be able to access the page served from a NAS within the network.

**Comment by pdobsan** [comment]
Use ssh port forwarding.

Anyway, this is not oama's problem. Closing it.
