### ISSUE TITLE
(Re-)Adding -c Paramter

### ISSUE THREAD

**Issue by OlMon** [pdobsan/oama#47]
Greetings, 

Thanks for working on this project!

Would it be possible to add the "-c" parameter to specify a config file?

Cheers,
OlMon

**Comment by pdobsan** [comment]
Yes, it would. I add it to my todo list. It is not obvious how to go about it now that oama automatically creates the config file if it's missing.

**Comment by OlMon** [comment]
Thanks a lot.

Would it not be enough to have the following logic:
- No -c parameter, keep everything as is.
- Provided -c:
   - Check if provided file exists/is valid -> if yes use it else fall back as no -c parameter were provided
   
I would like to create a PR but my Haskell is very rusty :(

Cheers!

**Comment by pdobsan** [comment]
On Sat, May 18, 2024 at 07:31:48AM GMT, OlMon wrote:
> Would it not be enough to have the following logic:
> - No -c parameter, keep everything as is.

Yes.

> - Provided -c:
>    - Check if provided file exists/is valid -> if yes use it else fall back as no -c parameter were provided

Almost. If provided file exists go (or possibly fail) with it else
create an initial config at this file path.

**Comment by OlMon** [comment]
> else create an initial config at this file path.
I am not sure this is a good idea.

There could be a typo in the path, will you create all parent directories to create the config file? Leaving the user with some not wanted filepath?
Or what is when the directory is Read-Only?
I think with your approach there will be much more edge cases to consider.

The behavior of most software that I know is the following:
There is a default config mostly somewhere in /etc/ and a custom config (if in user ~/.config directory or provided through parameters) is not working the default config is used. Or there is the hierarchy: parameters > ~/.config > default. 

That is just food for thought, I am glad you are considering adding the parameter.

Cheers!

**Comment by pdobsan** [comment]
I need both functionalities. However there will be a confirmation
question.

**Comment by pdobsan** [comment]
See [release 0.11.1](https://github.com/pdobsan/oama/releases/tag/0.11.1). No automatic creation of  --config given files.

**Comment by OlMon** [comment]
Works perfectly, thanks a lot!
