### ISSUE TITLE
Remove mention of GNOME keyring in favour of generic keyring backend mention.

### ISSUE THREAD

**Issue by siddhpant** [pdobsan/oama#56]
We just need a keyring backend / secret service. Mentioning "GNOME Keyring" can imply working only with it, when that's not the case. It works fine with keepassxc for example.

**Comment by pdobsan** [comment]
Right, it works  with any password manager which provides a FreeDesktop.org Secret Service compatible API. I am going to amend the docs.

**Comment by pdobsan** [comment]
docs has been amended

**Comment by siddhpant** [comment]
Thanks!

**Comment by siddhpant** [comment]
Just found out `oama authorize` still says `They have been stored in the Gome keyring ...` (it's also a typo :P)
