### ISSUE TITLE
add config options to bind to a fixed ip address and port

### ISSUE THREAD

**Issue by meehien** [pdobsan/oama#66]
Hi. Would it be possible to add configuration options for binding to a specific, fixed, ip address and port (instead of localhost and random port)? This would make remote configs easier to set up as one could use any network device to access oama.

**Comment by pdobsan** [comment]
> Hi. Would it be possible to add configuration options for binding to a specific, fixed, ip address and port (instead of localhost and random port)?

It is already configurable, see the Readme.

>This would make remote configs easier to set up as one could use any network device to access oama.

I don't see how, but would be curious if you succeed.

**Comment by meehien** [comment]
Apologies, but I don't seem to find it. I am referring to the ability to customize this link:
`http://localhost:<portnumber>/start `to something like `http://192.168.1.1:1234/start`. 

I am assuming that oama forwards the http traffic onto that port, so accessing that from the localhost, or from a different device would not make much difference (given that settings can be copied between devices, the token binds to oama and not the device itself). Hopefully I'm not completely misunderstanding how this works.

**Comment by meehien** [comment]
Thanks. The `redirect_uri:` is what I wanted. 

My goal was to see if I can remove the gui dependency for the `authorize ` command on the device running `oama`, for cases in which the token might expire. This however seems harder than I expected (as you hinted) because I am now failing some ip address checks (if I attempt the authorization from a different machine).

Until I understand OAuth2 better I will keep using your 'https://github.com/pdobsan/oama#running-oama-remotely' guide which does work quite well.

**Comment by pdobsan** [comment]
> My goal was to see if I can remove the gui dependency for the `authorize ` command on the device running `oama`,

Here is another way to achieve that. Chose a back-end, it can be either GPG or KEYRING. Make sure that the back-end installed and **works as desired**  on the remote machine. Pick a fixed `redirect_uri`, say, `http://localhost:3456`. Configure `oama` accordingly in the remote host.

Login into the remote host using the command below:
```
ssh -L 3456:localhost:3456 <remote-host>
```

Start the authorization on the *remote host* as usual:

```
oama authorize  ...
```

Then just follow the instructions and open the suggested URL in a browser running on the *local* machine.

**Comment by meehien** [comment]
This is quite neat. Thanks!

**Comment by pdobsan** [comment]
added ssh redirect method to readme
